# Generated by Django 6.0.3 on 2026-03-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_booking_bookingid_booking_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
