# Generated by Django 4.2.29 on 2026-03-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_otp_feedback_comment_blank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='rating',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
