# Generated by Django 4.2.29 on 2026-03-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_upi_id_and_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('unavailable', 'Not Available')], default='available', max_length=20),
        ),
    ]
