# Generated by Django 4.2.29 on 2026-03-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_provider_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='upi_id',
            field=models.CharField(default='n/a', max_length=100),
            preserve_default=False,
        ),
    ]
